server:
  port: 9710
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerlevel: FULL
      kakao: # FeignClient에서 name 설정값으로 준 값
        errorDecoder: com.study.springcloud.KakaoFeignClientErrorDecoder
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: FULL
#  okhttp:
#    enabled: true
  httpclient:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 요청에 대한 Timeout 설정
logging:
  level:
    com.study.springcloud.KakaoOpenApiClient: DEBUG
    com.study.springcloud.NoBodyFeignClient: DEBUG
spring:
  main:
    allow-bean-definition-overriding: true
