server:
  port: 9710
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerlevel: FULL
        connectTimeout: 1
        readTimeout: 1


logging:
  level:
    com.study.springcloud.KakaoOpenApiClient: DEBUG
